// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Blur_Blur,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.268000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=45,HLS_SYN_DSP=0,HLS_SYN_FF=8635,HLS_SYN_LUT=10445,HLS_VERSION=2020_2}" *)

module Blur (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        in_data_TDATA,
        in_data_TKEEP,
        in_data_TSTRB,
        in_data_TUSER,
        in_data_TLAST,
        in_data_TID,
        in_data_TDEST,
        out_data_TDATA,
        out_data_TKEEP,
        out_data_TSTRB,
        out_data_TUSER,
        out_data_TLAST,
        out_data_TID,
        out_data_TDEST,
        in_data_TVALID,
        in_data_TREADY,
        out_data_TVALID,
        out_data_TREADY
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
input  [23:0] in_data_TDATA;
input  [2:0] in_data_TKEEP;
input  [2:0] in_data_TSTRB;
input  [0:0] in_data_TUSER;
input  [0:0] in_data_TLAST;
input  [0:0] in_data_TID;
input  [0:0] in_data_TDEST;
output  [23:0] out_data_TDATA;
output  [2:0] out_data_TKEEP;
output  [2:0] out_data_TSTRB;
output  [0:0] out_data_TUSER;
output  [0:0] out_data_TLAST;
output  [0:0] out_data_TID;
output  [0:0] out_data_TDEST;
input   in_data_TVALID;
output   in_data_TREADY;
output   out_data_TVALID;
input   out_data_TREADY;

 reg    ap_rst_n_inv;
wire   [31:0] w;
wire   [31:0] h;
wire    Blur_entry9_U0_ap_start;
wire    Blur_entry9_U0_start_full_n;
wire    Blur_entry9_U0_ap_done;
wire    Blur_entry9_U0_ap_continue;
wire    Blur_entry9_U0_ap_idle;
wire    Blur_entry9_U0_ap_ready;
wire    Blur_entry9_U0_start_out;
wire    Blur_entry9_U0_start_write;
wire   [31:0] Blur_entry9_U0_w_out_din;
wire    Blur_entry9_U0_w_out_write;
wire   [31:0] Blur_entry9_U0_w_out1_din;
wire    Blur_entry9_U0_w_out1_write;
wire   [31:0] Blur_entry9_U0_h_out_din;
wire    Blur_entry9_U0_h_out_write;
wire   [31:0] Blur_entry9_U0_h_out2_din;
wire    Blur_entry9_U0_h_out2_write;
wire    Block_split549_proc_U0_ap_start;
wire    Block_split549_proc_U0_ap_done;
wire    Block_split549_proc_U0_ap_continue;
wire    Block_split549_proc_U0_ap_idle;
wire    Block_split549_proc_U0_ap_ready;
wire    Block_split549_proc_U0_start_out;
wire    Block_split549_proc_U0_start_write;
wire    Block_split549_proc_U0_w_read;
wire   [31:0] Block_split549_proc_U0_w_out_din;
wire    Block_split549_proc_U0_w_out_write;
wire   [31:0] Block_split549_proc_U0_vconv_xlim_out_out_din;
wire    Block_split549_proc_U0_vconv_xlim_out_out_write;
wire    Loop_HConvH_proc8_U0_ap_start;
wire    Loop_HConvH_proc8_U0_ap_done;
wire    Loop_HConvH_proc8_U0_ap_continue;
wire    Loop_HConvH_proc8_U0_ap_idle;
wire    Loop_HConvH_proc8_U0_ap_ready;
wire    Loop_HConvH_proc8_U0_h_read;
wire    Loop_HConvH_proc8_U0_w_read;
wire    Loop_HConvH_proc8_U0_in_data_TREADY;
wire   [23:0] Loop_HConvH_proc8_U0_hconv_din;
wire    Loop_HConvH_proc8_U0_hconv_write;
wire    Loop_VConvH_proc_U0_ap_start;
wire    Loop_VConvH_proc_U0_ap_done;
wire    Loop_VConvH_proc_U0_ap_continue;
wire    Loop_VConvH_proc_U0_ap_idle;
wire    Loop_VConvH_proc_U0_ap_ready;
wire    Loop_VConvH_proc_U0_h_read;
wire    Loop_VConvH_proc_U0_vconv_xlim_loc_read;
wire    Loop_VConvH_proc_U0_hconv_read;
wire   [23:0] Loop_VConvH_proc_U0_vconv_din;
wire    Loop_VConvH_proc_U0_vconv_write;
wire   [31:0] Loop_VConvH_proc_U0_h_out_din;
wire    Loop_VConvH_proc_U0_h_out_write;
wire   [31:0] Loop_VConvH_proc_U0_vconv_xlim_loc_out_din;
wire    Loop_VConvH_proc_U0_vconv_xlim_loc_out_write;
wire    Loop_Border_proc_U0_ap_start;
wire    Loop_Border_proc_U0_ap_done;
wire    Loop_Border_proc_U0_ap_continue;
wire    Loop_Border_proc_U0_ap_idle;
wire    Loop_Border_proc_U0_ap_ready;
wire    Loop_Border_proc_U0_h_read;
wire    Loop_Border_proc_U0_w_read;
wire    Loop_Border_proc_U0_vconv_xlim_loc_read;
wire   [23:0] Loop_Border_proc_U0_out_data_TDATA;
wire    Loop_Border_proc_U0_out_data_TVALID;
wire   [2:0] Loop_Border_proc_U0_out_data_TKEEP;
wire   [2:0] Loop_Border_proc_U0_out_data_TSTRB;
wire   [0:0] Loop_Border_proc_U0_out_data_TUSER;
wire   [0:0] Loop_Border_proc_U0_out_data_TLAST;
wire   [0:0] Loop_Border_proc_U0_out_data_TID;
wire   [0:0] Loop_Border_proc_U0_out_data_TDEST;
wire    Loop_Border_proc_U0_vconv_read;
wire    ap_sync_continue;
wire    w_c_full_n;
wire   [31:0] w_c_dout;
wire    w_c_empty_n;
wire    w_c566_full_n;
wire   [31:0] w_c566_dout;
wire    w_c566_empty_n;
wire    h_c_full_n;
wire   [31:0] h_c_dout;
wire    h_c_empty_n;
wire    h_c567_full_n;
wire   [31:0] h_c567_dout;
wire    h_c567_empty_n;
wire    w_c568_full_n;
wire   [31:0] w_c568_dout;
wire    w_c568_empty_n;
wire    vconv_xlim_loc_c_full_n;
wire   [31:0] vconv_xlim_loc_c_dout;
wire    vconv_xlim_loc_c_empty_n;
wire    hconv_full_n;
wire   [23:0] hconv_dout;
wire    hconv_empty_n;
wire    vconv_full_n;
wire   [23:0] vconv_dout;
wire    vconv_empty_n;
wire    h_c569_full_n;
wire   [31:0] h_c569_dout;
wire    h_c569_empty_n;
wire    vconv_xlim_loc_c570_full_n;
wire   [31:0] vconv_xlim_loc_c570_dout;
wire    vconv_xlim_loc_c570_empty_n;
wire   [0:0] start_for_Block_split549_proc_U0_din;
wire    start_for_Block_split549_proc_U0_full_n;
wire   [0:0] start_for_Block_split549_proc_U0_dout;
wire    start_for_Block_split549_proc_U0_empty_n;
wire   [0:0] start_for_Loop_HConvH_proc8_U0_din;
wire    start_for_Loop_HConvH_proc8_U0_full_n;
wire   [0:0] start_for_Loop_HConvH_proc8_U0_dout;
wire    start_for_Loop_HConvH_proc8_U0_empty_n;
wire   [0:0] start_for_Loop_VConvH_proc_U0_din;
wire    start_for_Loop_VConvH_proc_U0_full_n;
wire   [0:0] start_for_Loop_VConvH_proc_U0_dout;
wire    start_for_Loop_VConvH_proc_U0_empty_n;
wire   [0:0] start_for_Loop_Border_proc_U0_din;
wire    start_for_Loop_Border_proc_U0_full_n;
wire   [0:0] start_for_Loop_Border_proc_U0_dout;
wire    start_for_Loop_Border_proc_U0_empty_n;
wire    Loop_HConvH_proc8_U0_start_full_n;
wire    Loop_HConvH_proc8_U0_start_write;
wire    Loop_VConvH_proc_U0_start_full_n;
wire    Loop_VConvH_proc_U0_start_write;
wire    Loop_Border_proc_U0_start_full_n;
wire    Loop_Border_proc_U0_start_write;

Blur_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .w(w),
    .h(h)
);

Blur_Blur_entry9 Blur_entry9_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Blur_entry9_U0_ap_start),
    .start_full_n(Blur_entry9_U0_start_full_n),
    .ap_done(Blur_entry9_U0_ap_done),
    .ap_continue(Blur_entry9_U0_ap_continue),
    .ap_idle(Blur_entry9_U0_ap_idle),
    .ap_ready(Blur_entry9_U0_ap_ready),
    .start_out(Blur_entry9_U0_start_out),
    .start_write(Blur_entry9_U0_start_write),
    .w(w),
    .h(h),
    .w_out_din(Blur_entry9_U0_w_out_din),
    .w_out_full_n(w_c_full_n),
    .w_out_write(Blur_entry9_U0_w_out_write),
    .w_out1_din(Blur_entry9_U0_w_out1_din),
    .w_out1_full_n(w_c566_full_n),
    .w_out1_write(Blur_entry9_U0_w_out1_write),
    .h_out_din(Blur_entry9_U0_h_out_din),
    .h_out_full_n(h_c_full_n),
    .h_out_write(Blur_entry9_U0_h_out_write),
    .h_out2_din(Blur_entry9_U0_h_out2_din),
    .h_out2_full_n(h_c567_full_n),
    .h_out2_write(Blur_entry9_U0_h_out2_write)
);

Blur_Block_split549_proc Block_split549_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_split549_proc_U0_ap_start),
    .start_full_n(start_for_Loop_Border_proc_U0_full_n),
    .ap_done(Block_split549_proc_U0_ap_done),
    .ap_continue(Block_split549_proc_U0_ap_continue),
    .ap_idle(Block_split549_proc_U0_ap_idle),
    .ap_ready(Block_split549_proc_U0_ap_ready),
    .start_out(Block_split549_proc_U0_start_out),
    .start_write(Block_split549_proc_U0_start_write),
    .w_dout(w_c_dout),
    .w_empty_n(w_c_empty_n),
    .w_read(Block_split549_proc_U0_w_read),
    .w_out_din(Block_split549_proc_U0_w_out_din),
    .w_out_full_n(w_c568_full_n),
    .w_out_write(Block_split549_proc_U0_w_out_write),
    .vconv_xlim_out_out_din(Block_split549_proc_U0_vconv_xlim_out_out_din),
    .vconv_xlim_out_out_full_n(vconv_xlim_loc_c_full_n),
    .vconv_xlim_out_out_write(Block_split549_proc_U0_vconv_xlim_out_out_write)
);

Blur_Loop_HConvH_proc8 Loop_HConvH_proc8_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_HConvH_proc8_U0_ap_start),
    .ap_done(Loop_HConvH_proc8_U0_ap_done),
    .ap_continue(Loop_HConvH_proc8_U0_ap_continue),
    .ap_idle(Loop_HConvH_proc8_U0_ap_idle),
    .ap_ready(Loop_HConvH_proc8_U0_ap_ready),
    .h_dout(h_c_dout),
    .h_empty_n(h_c_empty_n),
    .h_read(Loop_HConvH_proc8_U0_h_read),
    .w_dout(w_c566_dout),
    .w_empty_n(w_c566_empty_n),
    .w_read(Loop_HConvH_proc8_U0_w_read),
    .in_data_TDATA(in_data_TDATA),
    .in_data_TVALID(in_data_TVALID),
    .in_data_TREADY(Loop_HConvH_proc8_U0_in_data_TREADY),
    .in_data_TKEEP(in_data_TKEEP),
    .in_data_TSTRB(in_data_TSTRB),
    .in_data_TUSER(in_data_TUSER),
    .in_data_TLAST(in_data_TLAST),
    .in_data_TID(in_data_TID),
    .in_data_TDEST(in_data_TDEST),
    .hconv_din(Loop_HConvH_proc8_U0_hconv_din),
    .hconv_full_n(hconv_full_n),
    .hconv_write(Loop_HConvH_proc8_U0_hconv_write)
);

Blur_Loop_VConvH_proc Loop_VConvH_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_VConvH_proc_U0_ap_start),
    .ap_done(Loop_VConvH_proc_U0_ap_done),
    .ap_continue(Loop_VConvH_proc_U0_ap_continue),
    .ap_idle(Loop_VConvH_proc_U0_ap_idle),
    .ap_ready(Loop_VConvH_proc_U0_ap_ready),
    .h_dout(h_c567_dout),
    .h_empty_n(h_c567_empty_n),
    .h_read(Loop_VConvH_proc_U0_h_read),
    .vconv_xlim_loc_dout(vconv_xlim_loc_c_dout),
    .vconv_xlim_loc_empty_n(vconv_xlim_loc_c_empty_n),
    .vconv_xlim_loc_read(Loop_VConvH_proc_U0_vconv_xlim_loc_read),
    .hconv_dout(hconv_dout),
    .hconv_empty_n(hconv_empty_n),
    .hconv_read(Loop_VConvH_proc_U0_hconv_read),
    .vconv_din(Loop_VConvH_proc_U0_vconv_din),
    .vconv_full_n(vconv_full_n),
    .vconv_write(Loop_VConvH_proc_U0_vconv_write),
    .h_out_din(Loop_VConvH_proc_U0_h_out_din),
    .h_out_full_n(h_c569_full_n),
    .h_out_write(Loop_VConvH_proc_U0_h_out_write),
    .vconv_xlim_loc_out_din(Loop_VConvH_proc_U0_vconv_xlim_loc_out_din),
    .vconv_xlim_loc_out_full_n(vconv_xlim_loc_c570_full_n),
    .vconv_xlim_loc_out_write(Loop_VConvH_proc_U0_vconv_xlim_loc_out_write)
);

Blur_Loop_Border_proc Loop_Border_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_Border_proc_U0_ap_start),
    .ap_done(Loop_Border_proc_U0_ap_done),
    .ap_continue(Loop_Border_proc_U0_ap_continue),
    .ap_idle(Loop_Border_proc_U0_ap_idle),
    .ap_ready(Loop_Border_proc_U0_ap_ready),
    .h_dout(h_c569_dout),
    .h_empty_n(h_c569_empty_n),
    .h_read(Loop_Border_proc_U0_h_read),
    .w_dout(w_c568_dout),
    .w_empty_n(w_c568_empty_n),
    .w_read(Loop_Border_proc_U0_w_read),
    .vconv_xlim_loc_dout(vconv_xlim_loc_c570_dout),
    .vconv_xlim_loc_empty_n(vconv_xlim_loc_c570_empty_n),
    .vconv_xlim_loc_read(Loop_Border_proc_U0_vconv_xlim_loc_read),
    .out_data_TDATA(Loop_Border_proc_U0_out_data_TDATA),
    .out_data_TVALID(Loop_Border_proc_U0_out_data_TVALID),
    .out_data_TREADY(out_data_TREADY),
    .out_data_TKEEP(Loop_Border_proc_U0_out_data_TKEEP),
    .out_data_TSTRB(Loop_Border_proc_U0_out_data_TSTRB),
    .out_data_TUSER(Loop_Border_proc_U0_out_data_TUSER),
    .out_data_TLAST(Loop_Border_proc_U0_out_data_TLAST),
    .out_data_TID(Loop_Border_proc_U0_out_data_TID),
    .out_data_TDEST(Loop_Border_proc_U0_out_data_TDEST),
    .vconv_dout(vconv_dout),
    .vconv_empty_n(vconv_empty_n),
    .vconv_read(Loop_Border_proc_U0_vconv_read)
);

Blur_fifo_w32_d2_S w_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Blur_entry9_U0_w_out_din),
    .if_full_n(w_c_full_n),
    .if_write(Blur_entry9_U0_w_out_write),
    .if_dout(w_c_dout),
    .if_empty_n(w_c_empty_n),
    .if_read(Block_split549_proc_U0_w_read)
);

Blur_fifo_w32_d2_S w_c566_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Blur_entry9_U0_w_out1_din),
    .if_full_n(w_c566_full_n),
    .if_write(Blur_entry9_U0_w_out1_write),
    .if_dout(w_c566_dout),
    .if_empty_n(w_c566_empty_n),
    .if_read(Loop_HConvH_proc8_U0_w_read)
);

Blur_fifo_w32_d2_S h_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Blur_entry9_U0_h_out_din),
    .if_full_n(h_c_full_n),
    .if_write(Blur_entry9_U0_h_out_write),
    .if_dout(h_c_dout),
    .if_empty_n(h_c_empty_n),
    .if_read(Loop_HConvH_proc8_U0_h_read)
);

Blur_fifo_w32_d3_S h_c567_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Blur_entry9_U0_h_out2_din),
    .if_full_n(h_c567_full_n),
    .if_write(Blur_entry9_U0_h_out2_write),
    .if_dout(h_c567_dout),
    .if_empty_n(h_c567_empty_n),
    .if_read(Loop_VConvH_proc_U0_h_read)
);

Blur_fifo_w32_d3_S w_c568_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_split549_proc_U0_w_out_din),
    .if_full_n(w_c568_full_n),
    .if_write(Block_split549_proc_U0_w_out_write),
    .if_dout(w_c568_dout),
    .if_empty_n(w_c568_empty_n),
    .if_read(Loop_Border_proc_U0_w_read)
);

Blur_fifo_w32_d2_S vconv_xlim_loc_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_split549_proc_U0_vconv_xlim_out_out_din),
    .if_full_n(vconv_xlim_loc_c_full_n),
    .if_write(Block_split549_proc_U0_vconv_xlim_out_out_write),
    .if_dout(vconv_xlim_loc_c_dout),
    .if_empty_n(vconv_xlim_loc_c_empty_n),
    .if_read(Loop_VConvH_proc_U0_vconv_xlim_loc_read)
);

Blur_fifo_w24_d2_S hconv_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_HConvH_proc8_U0_hconv_din),
    .if_full_n(hconv_full_n),
    .if_write(Loop_HConvH_proc8_U0_hconv_write),
    .if_dout(hconv_dout),
    .if_empty_n(hconv_empty_n),
    .if_read(Loop_VConvH_proc_U0_hconv_read)
);

Blur_fifo_w24_d2_S vconv_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_VConvH_proc_U0_vconv_din),
    .if_full_n(vconv_full_n),
    .if_write(Loop_VConvH_proc_U0_vconv_write),
    .if_dout(vconv_dout),
    .if_empty_n(vconv_empty_n),
    .if_read(Loop_Border_proc_U0_vconv_read)
);

Blur_fifo_w32_d2_S h_c569_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_VConvH_proc_U0_h_out_din),
    .if_full_n(h_c569_full_n),
    .if_write(Loop_VConvH_proc_U0_h_out_write),
    .if_dout(h_c569_dout),
    .if_empty_n(h_c569_empty_n),
    .if_read(Loop_Border_proc_U0_h_read)
);

Blur_fifo_w32_d2_S vconv_xlim_loc_c570_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_VConvH_proc_U0_vconv_xlim_loc_out_din),
    .if_full_n(vconv_xlim_loc_c570_full_n),
    .if_write(Loop_VConvH_proc_U0_vconv_xlim_loc_out_write),
    .if_dout(vconv_xlim_loc_c570_dout),
    .if_empty_n(vconv_xlim_loc_c570_empty_n),
    .if_read(Loop_Border_proc_U0_vconv_xlim_loc_read)
);

Blur_start_for_Block_split549_proc_U0 start_for_Block_split549_proc_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Block_split549_proc_U0_din),
    .if_full_n(start_for_Block_split549_proc_U0_full_n),
    .if_write(Blur_entry9_U0_start_write),
    .if_dout(start_for_Block_split549_proc_U0_dout),
    .if_empty_n(start_for_Block_split549_proc_U0_empty_n),
    .if_read(Block_split549_proc_U0_ap_ready)
);

Blur_start_for_Loop_HConvH_proc8_U0 start_for_Loop_HConvH_proc8_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Loop_HConvH_proc8_U0_din),
    .if_full_n(start_for_Loop_HConvH_proc8_U0_full_n),
    .if_write(Blur_entry9_U0_start_write),
    .if_dout(start_for_Loop_HConvH_proc8_U0_dout),
    .if_empty_n(start_for_Loop_HConvH_proc8_U0_empty_n),
    .if_read(Loop_HConvH_proc8_U0_ap_ready)
);

Blur_start_for_Loop_VConvH_proc_U0 start_for_Loop_VConvH_proc_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Loop_VConvH_proc_U0_din),
    .if_full_n(start_for_Loop_VConvH_proc_U0_full_n),
    .if_write(Blur_entry9_U0_start_write),
    .if_dout(start_for_Loop_VConvH_proc_U0_dout),
    .if_empty_n(start_for_Loop_VConvH_proc_U0_empty_n),
    .if_read(Loop_VConvH_proc_U0_ap_ready)
);

Blur_start_for_Loop_Border_proc_U0 start_for_Loop_Border_proc_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Loop_Border_proc_U0_din),
    .if_full_n(start_for_Loop_Border_proc_U0_full_n),
    .if_write(Block_split549_proc_U0_start_write),
    .if_dout(start_for_Loop_Border_proc_U0_dout),
    .if_empty_n(start_for_Loop_Border_proc_U0_empty_n),
    .if_read(Loop_Border_proc_U0_ap_ready)
);

assign Block_split549_proc_U0_ap_continue = 1'b1;

assign Block_split549_proc_U0_ap_start = start_for_Block_split549_proc_U0_empty_n;

assign Blur_entry9_U0_ap_continue = 1'b1;

assign Blur_entry9_U0_ap_start = 1'b1;

assign Blur_entry9_U0_start_full_n = (start_for_Loop_VConvH_proc_U0_full_n & start_for_Loop_HConvH_proc8_U0_full_n & start_for_Block_split549_proc_U0_full_n);

assign Loop_Border_proc_U0_ap_continue = 1'b1;

assign Loop_Border_proc_U0_ap_start = start_for_Loop_Border_proc_U0_empty_n;

assign Loop_Border_proc_U0_start_full_n = 1'b1;

assign Loop_Border_proc_U0_start_write = 1'b0;

assign Loop_HConvH_proc8_U0_ap_continue = 1'b1;

assign Loop_HConvH_proc8_U0_ap_start = start_for_Loop_HConvH_proc8_U0_empty_n;

assign Loop_HConvH_proc8_U0_start_full_n = 1'b1;

assign Loop_HConvH_proc8_U0_start_write = 1'b0;

assign Loop_VConvH_proc_U0_ap_continue = 1'b1;

assign Loop_VConvH_proc_U0_ap_start = start_for_Loop_VConvH_proc_U0_empty_n;

assign Loop_VConvH_proc_U0_start_full_n = 1'b1;

assign Loop_VConvH_proc_U0_start_write = 1'b0;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b0;

assign in_data_TREADY = Loop_HConvH_proc8_U0_in_data_TREADY;

assign out_data_TDATA = Loop_Border_proc_U0_out_data_TDATA;

assign out_data_TDEST = Loop_Border_proc_U0_out_data_TDEST;

assign out_data_TID = Loop_Border_proc_U0_out_data_TID;

assign out_data_TKEEP = Loop_Border_proc_U0_out_data_TKEEP;

assign out_data_TLAST = Loop_Border_proc_U0_out_data_TLAST;

assign out_data_TSTRB = Loop_Border_proc_U0_out_data_TSTRB;

assign out_data_TUSER = Loop_Border_proc_U0_out_data_TUSER;

assign out_data_TVALID = Loop_Border_proc_U0_out_data_TVALID;

assign start_for_Block_split549_proc_U0_din = 1'b1;

assign start_for_Loop_Border_proc_U0_din = 1'b1;

assign start_for_Loop_HConvH_proc8_U0_din = 1'b1;

assign start_for_Loop_VConvH_proc_U0_din = 1'b1;

endmodule //Blur
